version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: "ponpon_db"
    command: --init-file /data/application/init.sql
    ports:
    - 3306
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ponpon
      MYSQL_USER: m_user
      MYSQL_PASSWORD: m_password

  adminer:
    image: adminer
    container_name: "ponpon_adminer"
    ports:
      - 8080:8080